// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goshop/internal/dao/internal"
)

// internalSeckillCouponInfoDao is internal type for wrapping internal DAO implements.
type internalSeckillCouponInfoDao = *internal.SeckillCouponInfoDao

// seckillCouponInfoDao is the data access object for table seckill_coupon_info.
// You can define custom methods on it to extend its functionality as you wish.
type seckillCouponInfoDao struct {
	internalSeckillCouponInfoDao
}

var (
	// SeckillCouponInfo is globally public accessible object for table seckill_coupon_info operations.
	SeckillCouponInfo = seckillCouponInfoDao{
		internal.NewSeckillCouponInfoDao(),
	}
)

// Fill with you ideas below.
